openapi: 3.0.4
info:
  title: OData Service for namespace microsoft.graph - Subset - Subset
  description: This OData service is located at https://graph.microsoft.com/v1.0
  version: v1.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /admin/serviceAnnouncement/messages:
    get:
      tags:
        - admin.serviceAnnouncement
      summary: List serviceAnnouncement messages
      description: Retrieve the serviceUpdateMessage resources from the messages navigation property. This operation retrieves all service update messages that exist for the tenant.
      operationId: admin_serviceAnnouncement_ListMessages
      parameters:
        - name: $top
          in: query
          description: Show only the first n items
          explode: false
          schema:
            minimum: 0
            type: integer
          example: 50
        - name: $skip
          in: query
          description: Skip the first n items
          explode: false
          schema:
            minimum: 0
            type: integer
        - name: $search
          in: query
          description: Search items by search phrases
          explode: false
          schema:
            type: string
        - name: $filter
          in: query
          description: Filter items by property values
          explode: false
          schema:
            type: string
        - name: $count
          in: query
          description: Include count of items
          explode: false
          schema:
            type: boolean
        - name: $orderby
          in: query
          description: Order items by property values
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          description: Retrieved collection
          content:
            application/json:
              schema:
                title: Base collection pagination and count responses
                type: object
                properties:
                  '@odata.count':
                    type: integer
                    format: int64
                    nullable: true
                  '@odata.nextLink':
                    type: string
                    nullable: true
                  value:
                    type: array
                    items:
                      title: serviceUpdateMessage
                      required:
                        - '@odata.type'
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier for an entity. Read-only.
                        '@odata.type':
                          type: string
                        details:
                          type: array
                          items:
                            title: keyValuePair
                            required:
                              - '@odata.type'
                            type: object
                            properties:
                              name:
                                type: string
                                description: Name for this key-value pair
                              value:
                                type: string
                                description: Value for this key-value pair
                                nullable: true
                              '@odata.type':
                                type: string
                          description: More details about service event. This property doesn't support filters.
                        endDateTime:
                          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                          type: string
                          description: The end time of the service event.
                          format: date-time
                          nullable: true
                        lastModifiedDateTime:
                          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                          type: string
                          description: The last modified time of the service event.
                          format: date-time
                        startDateTime:
                          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                          type: string
                          description: The start time of the service event.
                          format: date-time
                        title:
                          type: string
                          description: The title of the service event.
                        actionRequiredByDateTime:
                          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                          type: string
                          description: The expected deadline of the action for the message.
                          format: date-time
                          nullable: true
                        attachmentsArchive:
                          type: string
                          description: The zip file that contains all attachments for a message.
                          format: base64url
                          nullable: true
                        body:
                          title: itemBody
                          required:
                            - '@odata.type'
                          type: object
                          properties:
                            content:
                              type: string
                              description: The content of the item.
                              nullable: true
                            contentType:
                              title: bodyType
                              enum:
                                - text
                                - html
                              type: string
                            '@odata.type':
                              type: string
                        category:
                          title: serviceUpdateCategory
                          enum:
                            - preventOrFixIssue
                            - planForChange
                            - stayInformed
                            - unknownFutureValue
                          type: string
                        hasAttachments:
                          type: boolean
                          description: Indicates whether the message has any attachment.
                        isMajorChange:
                          type: boolean
                          description: Indicates whether the message describes a major update for the service.
                          nullable: true
                        services:
                          type: array
                          items:
                            type: string
                            nullable: true
                          description: The affected services by the service message.
                        severity:
                          title: serviceUpdateSeverity
                          enum:
                            - normal
                            - high
                            - critical
                            - unknownFutureValue
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                            nullable: true
                          description: 'A collection of tags for the service message. Tags are provided by the service team/support team who post the message to tell whether this message contains privacy data, or whether this message is for a service new feature update, and so on.'
                        viewPoint:
                          title: serviceUpdateMessageViewpoint
                          required:
                            - '@odata.type'
                          type: object
                          properties:
                            isArchived:
                              type: boolean
                              description: Indicates whether the user archived the message.
                              nullable: true
                            isFavorited:
                              type: boolean
                              description: Indicates whether the user marked the message as favorite.
                              nullable: true
                            isRead:
                              type: boolean
                              description: Indicates whether the user read the message.
                              nullable: true
                            '@odata.type':
                              type: string
                        attachments:
                          type: array
                          items:
                            title: serviceAnnouncementAttachment
                            required:
                              - '@odata.type'
                            type: object
                            properties:
                              id:
                                type: string
                                description: The unique identifier for an entity. Read-only.
                              '@odata.type':
                                type: string
                              content:
                                type: string
                                description: The attachment content.
                                format: base64url
                                nullable: true
                              contentType:
                                type: string
                                nullable: true
                              lastModifiedDateTime:
                                pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                                type: string
                                format: date-time
                                nullable: true
                              name:
                                type: string
                                nullable: true
                              size:
                                maximum: 2147483647
                                minimum: -2147483648
                                type: number
                                format: int32
                          description: A collection of serviceAnnouncementAttachments.
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
        itemName: value
components: { }